### ISSUE TITLE
make revisions for Slack resubmission

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#76] opened 2017-08-25 21:41 UTC
[https://api.slack.com/apps/A6S70HLQ2/app-submission](https://api.slack.com/apps/A6S70HLQ2/app-submission)

>Revisions Needed
 Your app submission needs revisions before we can accept it for publication in the App 
 Directory. We’ve added comments about issues we’ve found so far; please submit again once 
 you’ve addressed them. You’re almost there!
 Slack Reviewer Notes
 Hello!
 After installing the app, it wasn't able to respond to times with a message. It appears as though 
 your app isn't requesting a scope like "chat:write:bot" which would be required to send something in Slack. Could you take a look at that and submit your app again when you're ready?

**Comment by jdrichardstech** [comment] 2017-08-25 21:43
do we need to add a chat:write:user or chat:write:bot to the scope?
[https://api.slack.com/docs/oauth-scopes](https://api.slack.com/docs/oauth-scopes)

**Comment by dsegovia90** [comment] 2017-08-28 17:07
Yeah, there was a bug that we were not asking for the user.info scope for the method `slack.user.info` so the app was crashing. Also refactored this code on all slack methods:
```
slack.users.info({ token, user }, (err, data) => {
  resolve(data); // This was always sending the resolve even if there was an error. 
  reject(err);
});
```
to => 
```
slack.users.info({ token, user }, (err, data) => {
  if (err) {
    reject(err);
  } else {
    resolve(data);
  }
});
```
Once you review this @jdrichardstech, please close the issue. I just wanted you to see the change, because I think it's important.

**Comment by jdrichardstech** [comment] 2017-08-28 19:20
yeah i see the difference. should check for error first in the callback. opposite of promise.

**Comment by dsegovia90** [comment] 2017-08-29 16:44
We need to get rid of the random link that is sometimes generated by (my best guess) godaddy redirect. We can catch it and redirect to where it should go.

**Comment by dsegovia90** [comment] 2017-08-29 16:45
![pasted image at 2017_08_28 05_38 pm](https://user-images.githubusercontent.com/14206991/29832959-7f169ef6-8caf-11e7-8e05-f14c808fda89.png)

**Comment by jdrichardstech** [comment] 2017-08-29 18:48
where do we do this? i'm a bit confused with this issue and why it is happening

BTW
On godaddy. I still see forwarding. I know you said that I made the mistake of forwarding instead of redirecting and you made changes. 
Should the forwarding still be on godaddy?
This is what I see on the godaddy account:

![screen shot 2017-08-29 at 2 45 41 pm](https://user-images.githubusercontent.com/1908887/29838362-fb18ef9a-8cc8-11e7-977b-954114dbd1f6.png)


![screen shot 2017-08-29 at 2 46 17 pm](https://user-images.githubusercontent.com/1908887/29838371-02f31f74-8cc9-11e7-8c96-7a151461fa4d.png)

**Comment by dsegovia90** [comment] 2017-08-29 19:12
it's not your mistake @jdrichardstech, the issue is from godaddy. I'll fix it in a bit. I'll explain what the issue is later on slack.

**Closed as completed** 2017-08-29 20:09 UTC
Labels: bug
